{% set name = "bunnet" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bunnet-{{ version }}.tar.gz
  sha256: e8e4aa61129c164f774a6549937f85507999cccef1a6591ac0ad175e695fe8c5

build:
  entry_points:
    - bunnet = bunnet.executors.migrate:migrations
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.7
    - pydantic >=1.9.0
    - pymongo
    - lazy-model >=0.0.3
    - click >=7
    - toml

test:
  imports:
    - bunnet
  commands:
    - pip check
    - bunnet --help
  requires:
    - pip

about:
  home: https://github.com/roman-right/bunnet
  summary: Synchronous Python ODM for MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
